name: example
description: Sup example app.

version: 1.1.0+1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sup:
    path: ../../sup
  url_launcher: ^6.0.2
  flutter_svg: ^0.19.3
  flare_flutter: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Chinese Rocks
      fonts:
        - asset: assets/fonts/chinese_rocks.ttf
